### ISSUE TITLE
Help Discord Server Invite Link Expired

### ISSUE THREAD

**Issue by FlyGuyGo** [Matt0550/VoiceMaster-Discord-Bot#1]
Hello, I am interested in joining your help Discord server. However, it appears that the link on the main page of the project is expired.

**Comment by Matt0550** [comment]
> Hello, I am interested in joining your help Discord server. However, it appears that the link on the main page of the project is expired.

Thank you for your interest, I’ll update the invitation link immediately and send it here too.

https://discord.gg/S87HpxGCvx

**Comment by FlyGuyGo** [comment]
Thank you!
